/* --------------------------- (C) COPYRIGHT 2021 Fortiortech ShenZhen -----------------------------
    File Name      : ADCInit.h
    Author         : Lewis。wang
    Version        : V1.0
    Date           : 2021-12-28
    Description    : This file contains ADC parameter used for Motor Control.
----------------------------------------------------------------------------------------------------
                                       All Rights Reserved
------------------------------------------------------------------------------------------------- */

/* Define to prevent recursive inclusion -------------------------------------------------------- */
#ifndef __A_D_C_H_
#define __A_D_C_H_

extern void ADC_Init(void);

#endif

