/* --------------------------- (C) COPYRIGHT 2021 Fortiortech ShenZhen -----------------------------
    File Name      : AMPInit.h
    Author         : Lewis。wang
    Version        : V1.0
    Date           : 2021-12-28
    Description    : This file contains AMP parameter used for Motor Control.
----------------------------------------------------------------------------------------------------
                                       All Rights Reserved
------------------------------------------------------------------------------------------------- */

/* Define to prevent recursive inclusion -------------------------------------------------------- */
#ifndef __A_M_P_H_
#define __A_M_P_H_

extern void AMP_Init(void);

#endif






