/* --------------------------- (C) COPYRIGHT 2021 Fortiortech ShenZhen -----------------------------
    File Name      : CMPInit.h
    Author         : Lewis.wang
    Version        : V1.0
    Date           : 2021-12-28
    Description    : This file contains CMP parameter used for Motor Control.
----------------------------------------------------------------------------------------------------
                                       All Rights Reserved
------------------------------------------------------------------------------------------------- */

/* Define to prevent recursive inclusion -------------------------------------------------------- */
#ifndef __C_M_P_H_
#define __C_M_P_H_

extern void CMP0_Init(void);
extern void CMP3_Init(void);
extern void CMP3_Interrupt_Init(void);

#endif




