/* --------------------------- (C) COPYRIGHT 2021 Fortiortech ShenZhen -----------------------------
    File Name      : DriverInit.h
    Author         : Lewis.wang
    Version        : V1.0
    Date           : 2021-12-28
    Description    : This file contains Driver parameter used for Motor Control.
----------------------------------------------------------------------------------------------------
                                       All Rights Reserved
------------------------------------------------------------------------------------------------- */
#ifndef __DRIVER_H_
#define __DRIVER_H_

extern void Driver_Init(void);

#endif



